//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InvestorUniverse.Models
{
    using System;
    using System.Collections.Generic;

   
    public partial class Contact
    {
        public int ContactId { get; set; }
        public Nullable<int> InvestorId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Title { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string Job_Title { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<double> Zip_Code { get; set; }
        public string Investor { get; set; }
        public string Country { get; set; }
    
        public virtual CompanyType CompanyType { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Investor Investor1 { get; set; }
    }
}
