//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestorUniverse.Models
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;

    [MetadataType(typeof(CountryMetaData))]
    public partial class Country
    {
        public Country()
        {
            this.Contacts = new HashSet<Contact>();
            this.Investors = new HashSet<Investor>();
        }

        public int Id { get; set; }

        [Display(Name = "Country")]
        public string Country1 { get; set; }

        [Display(Name = "Created On")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> CreatedOn { get; set; }

        [Display(Name = "Created By")]
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }

        [Display(Name = "ModifiedBy By")]
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Investor> Investors { get; set; }
    }
}
