//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using System.ComponentModel.DataAnnotations;
namespace InvestorUniverse.Models
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(CurrencyMetaData))]
    public partial class Currency
    {
        public Currency()
        {
            this.Investors = new HashSet<Investor>();
            this.Investors1 = new HashSet<Investor>();
            this.Investors2 = new HashSet<Investor>();
            this.Investors3 = new HashSet<Investor>();
        }
    
        public int Id { get; set; }
        public string Currency1 { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual ICollection<Investor> Investors { get; set; }
        public virtual ICollection<Investor> Investors1 { get; set; }
        public virtual ICollection<Investor> Investors2 { get; set; }
        public virtual ICollection<Investor> Investors3 { get; set; }
    }
}
