//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace InvestorUniverse.Models
{
    using System;
    using System.Collections.Generic;

    [MetadataType(typeof(InvestorMetaData))]
    public partial class Investor
    {
        public Investor()
        {
            this.Contacts = new HashSet<Contact>();
            this.InvestorIndustries = new HashSet<InvestorIndustry>();
            this.InvestorRegions = new HashSet<InvestorRegion>();
            this.InvestorStages = new HashSet<InvestorStage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> PEInvestingId { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<int> RegionId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<double> Zip_Code { get; set; }
        public Nullable<int> CountryId { get; set; }
        public string Web { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Fax { get; set; }
        public Nullable<double> Funds_under_Mgmt__mn_ { get; set; }
        public Nullable<int> FundUnderManagementCurrencyId { get; set; }
        public Nullable<double> Funds_under_Mgmt__mn_USD_ { get; set; }
        public Nullable<double> Funds_under_Mgmt__mn_EUR_ { get; set; }
        public Nullable<double> Current_Allocation_to_PE____ { get; set; }
        public Nullable<double> Current_Allocation_to_PE__mn_USD_ { get; set; }
        public Nullable<double> Current_Allocation_to_PE__mn_EUR_ { get; set; }
        public string Target_Allocation_to_PE____ { get; set; }
        public string Target_Allocation_to_PE__mn_USD_ { get; set; }
        public string Target_Allocation_to_PE__mn_EUR_ { get; set; }
        public string Separate_Accounts_Committed_Capital___ { get; set; }
        public string Separate_Accounts_Committed_Capital_USD_ { get; set; }
        public string Separate_Accounts_Committed_Capital_EUR_ { get; set; }
        public string Typical_Investment_Size__mn_ { get; set; }
        public string Fund_Preferences { get; set; }
        public string Geographic_Preferences { get; set; }
        public Nullable<int> FirstTimeId { get; set; }
        public Nullable<int> FirstCloseId { get; set; }
        public string First_Close_Investor { get; set; }
        public Nullable<int> SeparateAccountId { get; set; }
        public Nullable<int> CoInvestmentsId { get; set; }
        public string Co_Invest_with_GP { get; set; }
        public Nullable<int> Next12MonthCurrencyId { get; set; }
        public Nullable<double> Next_12_Months_Amount_min__mn_ { get; set; }
        public Nullable<double> Next_12_Months_Amount_max__mn_ { get; set; }
        public Nullable<double> Next_12_Months_Amount___mn__min { get; set; }
        public Nullable<double> Next_12_Months_Amount___mn__max { get; set; }
        public Nullable<double> Next_12_Months_Number_of_Funds__min_ { get; set; }
        public Nullable<double> Next_12_Months_Number_of_Funds__max_ { get; set; }
        public string Next_12_Months___Fund_Type_Preferences { get; set; }
        public Nullable<System.DateTime> Date_of_12_Month_Plan { get; set; }
        public string General_Consultants { get; set; }
        public string Private_Equity_Consultants { get; set; }
        public Nullable<int> Stage { get; set; }
        public Nullable<int> RFPOutcome { get; set; }
        public Nullable<int> AbbottPerson { get; set; }
        public Nullable<int> MeetingFrequency { get; set; }
        public Nullable<int> Priority { get; set; }
    
        public virtual AbbottPerson AbbottPerson1 { get; set; }
        public virtual Coinvestment Coinvestment { get; set; }
        public virtual CompanyType CompanyType { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual Country Country { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Currency Currency1 { get; set; }
        public virtual Currency Currency2 { get; set; }
        public virtual Currency Currency3 { get; set; }
        public virtual FirstClose FirstClose { get; set; }
        public virtual FirstTime FirstTime { get; set; }
        public virtual ICollection<InvestorIndustry> InvestorIndustries { get; set; }
        public virtual ICollection<InvestorRegion> InvestorRegions { get; set; }
        public virtual MeetingFrequency MeetingFrequency1 { get; set; }
        public virtual PEInvesting PEInvesting { get; set; }
        public virtual Priority Priority1 { get; set; }
        public virtual Region Region { get; set; }
        public virtual RFPOutCome RFPOutCome1 { get; set; }
        public virtual SeparateAccount SeparateAccount { get; set; }
        public virtual Stage Stage1 { get; set; }
        public virtual ICollection<InvestorStage> InvestorStages { get; set; }
    }
}
