//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestorUniverse.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketingEntities : DbContext
    {
        public MarketingEntities()
            : base("name=MarketingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AbbottPerson> AbbottPersons { get; set; }
        public virtual DbSet<Coinvestment> Coinvestments { get; set; }
        public virtual DbSet<CompanyType> CompanyTypes { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<FirstClose> FirstCloses { get; set; }
        public virtual DbSet<FirstTime> FirstTimes { get; set; }
        public virtual DbSet<Intralink> Intralinks { get; set; }
        public virtual DbSet<InvestorNote> InvestorNotes { get; set; }
        public virtual DbSet<MailingList> MailingLists { get; set; }
        public virtual DbSet<MeetingFrequency> MeetingFrequencies { get; set; }
        public virtual DbSet<PEInvesting> PEInvestings { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<ProductList> ProductLists { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<RFPOutCome> RFPOutComes { get; set; }
        public virtual DbSet<SeparateAccount> SeparateAccounts { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<InvestorStage> InvestorStages { get; set; }
        public virtual DbSet<Industry> Industries { get; set; }
        public virtual DbSet<InvestorIndustry> InvestorIndustries { get; set; }
        public virtual DbSet<InvestorRegion> InvestorRegions { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<Investor> Investors { get; set; }
    }
}
